name: CI para Cafetería Flask

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install flask flask_sqlalchemy flask_login flask_bcrypt flask_caching
        pip install bandit pylint pytest

    - name: Análisis de seguridad (Bandit)
      run: bandit -r .

    - name: Linter (Pylint)
      run: pylint *.py routes/*.py

    - name: Ejecutar pruebas (si tienes test)
      run: pytest || echo "No se encontraron pruebas"

